#!/usr/bin/env python3


def main():
    grade = int(input("Enter your grade: "))

    if grade >= 90:
        print("Your grade is A")
    elif grade >= 80:
        print("Your grade is B")
    elif grade >= 70:
        print("Your grade is C")
    elif grade >= 60:
        print("Your grade is D")
    else:
        print("Your grade is F")


if __name__ == "__main__":
    main()

