#!/usr/bin/env python3

def get_test_feedback():
    """
    Provide feedback based on a student's test score.

    Steps:
    1. Get the user input as an integer of the student's score.
    2. Use a primary if statement to check if the score is higher than 0.
       Inside this if statement, use nested conditionals to determine the
       feedback message based on these conditions:
       - If the score is greater than 90, print 'Excellent!'.
       - If the score is between 70 and 90 (inclusive), print 'Good job!'.
       - If the score is less than 70, print 'Keep working hard!'.
    3. If no score is provided (score equals 0), print 'No test score available'.
    """
    test_score = int(input("Enter your test score: "))
    if test_score > 0:         # Outer if
        if test_score > 90:    # Inner if 1
            print("Excellent!")
            # between 70 and 90 ... good job!
        elif test_score >= 70 and test_score <= 90: # inner elif
            print("Good job!")
            # if not between 70 and 90, print 'Keep working hard!'
        else:                   # Inner else (covers 1-69)
            print("Keep working hard!")
            # if not between 0 and 90, print 'No test score available'
    else:                       # Outer else (covers <= 0)
        print("No test score available")



def main():
    get_test_feedback()



if __name__ == "__main__":
    main()
